2022/11/04 09:27:11 [error] 311#311: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: nextcloud.*, request: "GET / HTTP/2.0", upstream: "https://172.18.0.4:443/", host: "nextcloud.test6482.duckdns.org"
2022/11/04 09:27:13 [error] 311#311: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: nextcloud.*, request: "GET /favicon.ico HTTP/2.0", upstream: "https://172.18.0.4:443/favicon.ico", host: "nextcloud.test6482.duckdns.org", referrer: "https://nextcloud.test6482.duckdns.org/"
2022/11/04 09:27:17 [error] 311#311: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: nextcloud.*, request: "GET / HTTP/2.0", upstream: "https://172.18.0.4:443/", host: "nextcloud.test6482.duckdns.org"
2022/11/04 09:27:17 [error] 311#311: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: nextcloud.*, request: "GET /favicon.ico HTTP/2.0", upstream: "https://172.18.0.4:443/favicon.ico", host: "nextcloud.test6482.duckdns.org", referrer: "https://nextcloud.test6482.duckdns.org/"
2022/11/04 10:28:13 [error] 287#287: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: gitea.*, request: "GET /user/login HTTP/2.0", upstream: "http://172.18.0.8:3000/user/login", host: "gitea.test6482.duckdns.org"
2022/11/04 10:28:13 [error] 287#287: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: gitea.*, request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.8:3000/favicon.ico", host: "gitea.test6482.duckdns.org", referrer: "https://gitea.test6482.duckdns.org/user/login"
2022/11/12 12:39:19 [error] 288#288: *1 heimdall could not be resolved (2: Server failure), client: 10.0.2.2, server: heimdall.*, request: "GET / HTTP/2.0", host: "heimdall.test6482.duckdns.org"
2022/11/12 12:39:19 [error] 288#288: *1 heimdall could not be resolved (2: Server failure), client: 10.0.2.2, server: heimdall.*, request: "GET /favicon.ico HTTP/2.0", host: "heimdall.test6482.duckdns.org", referrer: "https://heimdall.test6482.duckdns.org/"
2022/11/12 12:41:35 [error] 288#288: *92 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: nextcloud.*, request: "GET / HTTP/2.0", upstream: "https://172.18.0.10:443/", host: "nextcloud.test6482.duckdns.org"
2022/11/12 12:41:36 [error] 288#288: *92 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: nextcloud.*, request: "GET /favicon.ico HTTP/2.0", upstream: "https://172.18.0.10:443/favicon.ico", host: "nextcloud.test6482.duckdns.org", referrer: "https://nextcloud.test6482.duckdns.org/"
2022/11/12 16:27:57 [error] 288#288: *1 plik could not be resolved (2: Server failure), client: 10.0.2.2, server: plik.*, request: "GET / HTTP/2.0", host: "plik.test6482.duckdns.org"
2022/11/12 16:27:59 [error] 288#288: *1 plik could not be resolved (2: Server failure), client: 10.0.2.2, server: plik.*, request: "GET /favicon.ico HTTP/2.0", host: "plik.test6482.duckdns.org", referrer: "https://plik.test6482.duckdns.org/"
2022/11/12 16:28:02 [error] 288#288: *1 plik could not be resolved (2: Server failure), client: 10.0.2.2, server: plik.*, request: "GET / HTTP/2.0", host: "plik.test6482.duckdns.org"
2022/11/12 16:28:02 [error] 288#288: *1 plik could not be resolved (2: Server failure), client: 10.0.2.2, server: plik.*, request: "GET /favicon.ico HTTP/2.0", host: "plik.test6482.duckdns.org", referrer: "https://plik.test6482.duckdns.org/"
2022/11/12 16:28:04 [error] 288#288: *1 plik could not be resolved (2: Server failure), client: 10.0.2.2, server: plik.*, request: "GET / HTTP/2.0", host: "plik.test6482.duckdns.org"
2022/11/12 16:28:04 [error] 288#288: *1 plik could not be resolved (2: Server failure), client: 10.0.2.2, server: plik.*, request: "GET /favicon.ico HTTP/2.0", host: "plik.test6482.duckdns.org", referrer: "https://plik.test6482.duckdns.org/"
2022/11/12 16:32:17 [error] 288#288: *1 plik could not be resolved (2: Server failure), client: 10.0.2.2, server: plik.*, request: "GET / HTTP/2.0", host: "plik.test6482.duckdns.org"
2022/11/12 16:32:17 [error] 288#288: *1 plik could not be resolved (2: Server failure), client: 10.0.2.2, server: plik.*, request: "GET /favicon.ico HTTP/2.0", host: "plik.test6482.duckdns.org", referrer: "https://plik.test6482.duckdns.org/"
2022/11/12 16:32:28 [error] 288#288: *1 plik could not be resolved (2: Server failure), client: 10.0.2.2, server: plik.*, request: "GET /favicon.ico HTTP/2.0", host: "plik.test6482.duckdns.org", referrer: "https://plik.test6482.duckdns.org/"
2022/11/12 16:32:30 [error] 288#288: *1 plik could not be resolved (2: Server failure), client: 10.0.2.2, server: plik.*, request: "GET / HTTP/2.0", host: "plik.test6482.duckdns.org"
2022/11/12 16:32:30 [error] 288#288: *1 plik could not be resolved (2: Server failure), client: 10.0.2.2, server: plik.*, request: "GET /favicon.ico HTTP/2.0", host: "plik.test6482.duckdns.org", referrer: "https://plik.test6482.duckdns.org/"
